### ISSUE TITLE
[BUG]: Website link is broken

### ISSUE THREAD

**Issue by FrozenHearth** [soundise/react-components#19]
### Describe the bug

I'm getting a `DNS_PROBE_FINISHED_NXDOMAIN` error when I go to components.soundise.com

### To Reproduce

1. Go to components.soundise.com
2. Observe the `DNS_PROBE_FINISHED_NXDOMAIN` error

### Expected behavior

Navigating to the website shouldn't throw an error.

### Screenshots

<img width="1781" alt="Screenshot 2023-01-02 at 1 54 27 AM" src="https://user-images.githubusercontent.com/27160715/210183702-a06a269f-2e7e-4179-98c6-918143db396f.png">

### Desktop

- OS [e.g. Arch]: Mac OSX Monterey 12.5.1
- Browser [e.g. Firefox]: Chrome
- Version [e.g. 107.0.1]: 108.0.5359.124

**Comment by olekbaran** [comment]
Hi @FrozenHearth 

Actually, we have not yet finished working on the components.soundise.com website, which is the reason it is not functioning correctly.

Meanwhile, we will consider setting up a maintenance page or under construction page to inform visitors that the website is currently being worked on and will be available at a later time. This can help prevent any confusion or frustration for your users.

**Comment by FrozenHearth** [comment]
Having a maintenance or under construction page would be fantastic! Thanks.
